# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Athletics-List-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Athletics-List-iOS
  pod 'SwiftyJSON'
  pod 'SDWebImage', '~> 4.0'
  pod 'Alamofire', '~> 4.5'

end
